# Generated by Django 4.1.5 on 2024-01-30 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filldetailsmodels',
            old_name='file',
            new_name='fileInput',
        ),
    ]
