# Generated by Django 4.1.5 on 2024-01-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_rename_file_filldetailsmodels_fileinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filldetailsmodels',
            name='fileInput',
            field=models.FileField(upload_to='media/'),
        ),
    ]
