# Generated by Django 4.1.5 on 2024-02-17 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_alter_filldetailsmodels_fileinput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filldetailsmodels',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='filldetailsmodels',
            name='file_detail',
        ),
        migrations.RemoveField(
            model_name='filldetailsmodels',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='filldetailsmodels',
            name='phone_no',
        ),
    ]
