# Generated by Django 4.1.5 on 2024-02-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_rename_first_name_filldetailsmodels_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('pass1', models.CharField(max_length=10)),
                ('pass2', models.CharField(max_length=10)),
            ],
        ),
    ]
